# Use the official WildFly 10.1.0 image
FROM jboss/wildfly:10.1.0.Final  

# Copy StudentInfo.html to the default WildFly welcome content directory
COPY StudentInfo.html /opt/jboss/wildfly/welcome-content/